version: '3.7'

services:
    php:
        build: docker/php
        ports:
            - "9000:9000"
        volumes:
            - project:/var/www/app:consistent
            - docker_logs:/var/www/app/var/log:consistent
        links:
            - mysql
        extra_hosts:
            - "car.localhost:192.168.1.69"

    nginx:
        build: docker/nginx
        ports:
            - "8080:80"
        links:
            - php
        volumes:
            - project:/var/www/app:consistent
            - docker_logs:/var/log/nginx:consistent
    mysql:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        ports:
          - "3306:3306"
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: test
            MYSQL_USER: test
            MYSQL_PASSWORD: test
            MYSQL_DATABASE: test

    redis:
        image: redis

volumes:
  project:
  docker_logs:
