CREATE DATABASE audi;
CREATE USER audi@localhost IDENTIFIED BY 'audi';
GRANT ALL PRIVILEGES ON *.* TO audi@'%' IDENTIFIED BY 'audi';
GRANT ALL PRIVILEGES ON *.* TO audi@localhost IDENTIFIED BY 'audi';
FLUSH PRIVILEGES;
